"""renomear campo produtos da tabela carrinho

Revision ID: e8f57ee61989
Revises: c8b3af7652d3
Create Date: 2026-04-21 18:37:59.543849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f57ee61989'
down_revision: Union[str, Sequence[str], None] = 'c8b3af7652d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
